---
galaxy_info:
  role_name: fsbuilder
  author: Sean
  description: >-
    Role wrapper for the fsbuilder module providing role-level
    plugin discovery via symlinks.
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions: [8, 9]
    - name: Ubuntu
      versions: [20.04, 22.04, 24.04]
    - name: Debian
      versions: [11, 12]
dependencies: []
